[package]
name = "pbdb-macros"
version = "0.1.0"
edition = "2018"
build = "build.rs"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.27"
prost = "0.8.0"
quote = "1.0.9"

[build-dependencies]
prost-build = "0.8.0"
