[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pbdb = { version = "0.1.0", path = ".." }
prost = "0.9.0"

[build-dependencies]
prost-build = "0.9.0"
pbdb = { version = "0.1.0", path = ".." }

[dev-dependencies]
tempfile = "3.2.0"
